### ISSUE TITLE
Wardrobe Unlock Analyser down?

### ISSUE THREAD

**Issue by Valera512** [immortius/gw2-wardrobe-unlock#12]
It doesn't seem to be available at least since yesterday.

**Comment by ShiningMassXAcc** [comment]
@Valera512 - there was a banner on the site some time ago that said it was moving.  I can't recall what is was, and the about link on github still points to the old one.

**Comment by denchen** [comment]
It seems the new website is at https://immortius.xyz/wardrobe-unlock-analyser/
