### ISSUE TITLE
Item prices far off actual values

### ISSUE THREAD

**Issue by Aussiemon** [immortius/gw2-wardrobe-unlock#23]
Screenshot:
![image](https://user-images.githubusercontent.com/13663574/170568037-fd3daa31-7bd2-4838-8f5d-5e6d765b5f89.png)

Examples:
[Scepter of Thorn](https://wiki.guildwars2.com/index.php?title=Scepter_of_Thorn) is 0 copper if you own the outfit, but the outfit is 700 gems and currently unavailable.

[Ancient Ritualist Mantle](https://wiki.guildwars2.com/wiki/Ancient_Ritualist_Mantle) is listed as 0g55s63c, but the only method of acquiring the skin is through the armor piece, which currently has a trading post buy value of 8g18s84c and a crafting value of 9g24s87c. 

[Tempest Short Bow](https://wiki.guildwars2.com/wiki/Tempest_Short_Bow_Skin) is listed as 8g5s24c, but currently has a trading post buy value of 14g37s03c and a vendor value of 5 BL claim tickets.

These items have all been at or around these values for several weeks, so these discrepancies aren't due to price fluctuations.

**Comment by immortius** [comment]
Thanks for this list.

- It seems the black lion exchange npc entry on the wiki was renamed, so I've updated my filter to exclude them again.
- Otherwise it looks like updates haven't been uploading to the site... I need to add better alerting for that.
