### ISSUE TITLE
Error on API load

### ISSUE THREAD

**Issue by antocs** [immortius/gw2-wardrobe-unlock#38]
![image](https://user-images.githubusercontent.com/22413659/220286887-f06c69f7-9c64-4325-a15d-0a3633cdef45.png)
It throws this error when loading the API info, it shows the skins loading, then throws the error and back to 0/xxxx, also tried with a new API key.

**Comment by immortius** [comment]
The account emotes endpoint needs your API key to have the progression permission, is that the case?

Edit: I guess there is a bug that sections other than emotes are losing their status either way.

**Comment by antocs** [comment]
Didn't notice in now requires progression endpoint too, all good now!
